<div class="custom-tab">
    <div class="actions dropdown">
        <span
            class="action toggle"
            data-mage-init='{"dropdown":{}}'
            data-toggle="dropdown"
            aria-haspopup="true">
        <span>Choose one</span>
    </span>
        <ul class="dropdown">
            <li>
                <span class="item">One</span>
            </li>
            <li>
                <span class="item">Two</span>
            </li>
            <li>
                <span class="item">Three</span>
            </li>
        </ul>
    </div>
</div>